spring:
  application:
    name: contact-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'